---
title: "Retinalogik vs HFA study"
author: "[Eadie Technologies, Inc.](https://www.eadietech.com/)"
date: "2025-02-06"
output: 
  html_document:
    theme: yeti
    code_folding: hide
    toc: true
    toc_depth: 2
    toc_float: 
      collapsed: true
    includes:
        after_body: footer.html
---

## Setup

### Versioning

Last updated on `r format(Sys.time(), '%Y-%b-%d')` at `r format(Sys.time(), '%I:%M %p')`.

* 2025-Feb-06: Created git & RStudio project

### Acknowledgements
Data collected by Research Assistant Reann Post and Research Coordinator Lynn Murphy.

```{r setup, collapse=TRUE}

# load packages
library(tidyverse)
library(here)
library(DT)
library(plotly)
library(viridis)
library(svglite)
library(htmltools)

sessionInfo()

# default chunk options
knitr::opts_chunk$set(
  comment = '>', cache = TRUE, collapse = TRUE, cache = FALSE, dev= c("png")
  )

# load processed data
load(here("dBdat.Rda"))

```

# Study summary
We compared 24-2 Full Threshold visual field (VF) test results between Retinalogik and Humphrey Field Analyzer (HFA) in patients with early glaucoma and moderate to advanced glaucoma.

# Methods (briefly)
## Subjects

Eligible participants were identified among patients who are patients of Dr. Brennan Eadie at the Eadie Eye Centre. If deemed eligible for the study, subjects were recruited consecutively.

Each participant underwent 5 study visits, whereupon they performed a VF test on both eyes, on both devices, with the order of devices randomized during the baseline 1st study visit.

The study adhered to the tenets of the Declaration of Helsinki for research involving human subjects and the protocol was approved by the Nova Scotia Health Research Ethics Board (#1024439). All participants gave their written informed consent before enrollment in the study.

## Analysis
All OS data were transposed to OD format before analyses. A total of `r dBdat %>% group_by(id, age, eye, device) %>% distinct(duration) %>% nrow()` datasets were collected from `r length(unique(dBdat$id))` participants with mean age of `r mean(dBdat$age)`.
